### ISSUE TITLE
Budding blocks don't grow crystals except for larimar budding block

### ISSUE THREAD

**Issue by emerysleeper** [AetherLegacyPro/NovaCraft#1]
The problem might be in the nexc parts of the code:

`public class BlockBuddingCopartz extends BlockLarimar {`

and 

`if (block instanceof BlockLarimarCluster && meta % 6 == facing.ordinal()) {`

Copartz block extends Larimar, and the check for instance of cluster is for Larimar too.

The same applies to every other budding block, except Larimar - Larimar extends Larimar and checks for Larimar Cluster.

**Comment by AetherLegacyPro** [comment]
![image](https://github.com/user-attachments/assets/718e67a4-7a71-41d3-bc72-331abb8f13c8)

Well forgot about that part, what I get for putting the budding blocks, blocks and clusters in the same package... Thank you for the bug report, I have fixed it. Do you want me to upload a patch with it soon? I plan to upload V1.4 hopefully around Christmas.

**Comment by emerysleeper** [comment]
Great! No, no need to hurry.
I have a question regarding other stuff from the mod, like rituals. I can see the gallery on Modrinth, and I've tried some rituals like null block ritual, or Warden ritual (in creative, Warden altar doesn't have a recipe), to no avail. Do you have any plans to make a wiki or explain rituals more in-depth?

**Comment by emerysleeper** [comment]
I see. As for the ritual for the null buds - they are dimension dependent, but they require Budding Aether, right? As I see in code, aether buds might require dimension ID 4 (screenshot applied), but the End is dimensionID 1. Is it on purpose? Will they truly grow in End? They don't in my instance (1.3.5), unless I change the code to dimensionID 1.
The code on GitHub:
![image](https://github.com/user-attachments/assets/af888676-c0a8-4c05-8b52-79125e4f07ed)
Without changing the code, ingame:
![image](https://github.com/user-attachments/assets/5a9eec95-00ed-4083-a1e3-cbe63e281b26)
With changing the code, ingame (the ritual still doesn't work for some reason, will try to see if I did something wrong through your youtube channel):
![image](https://github.com/user-attachments/assets/ae2759bd-cad6-4c73-a08d-ec2c448c8412)

**Comment by AetherLegacyPro** [comment]
Ya the rituals with the 4 different crystals is not very clear about the direction they should be placed in. 

The block that is placed in the center must be an echo block not budding echo, surrond it in sculk tentacles on sculk endstone. In the +X +Z direction is where the orange crystal goes. All crystals below it are budding blocks. Then you place a grown echo cluster on the echo block  Only can be done in the End.

They activate after a certain number of ticks to avoid it causing lag if it checking it all the time, performance mods slow it down even further, I will change them to be actived with something in the future like how the Warden is summoned.

You would grow the Aether buds in either the overworld or aether and then use silk touch on the grown clusters to bring them into the End in survival.

The echo block class should tell you what it is checking for to ensure it is correct, it is likely just being slow to activate.

**Comment by emerysleeper** [comment]
Didn't understand about +X +Z at first, and didn't know I should manually place echo cluster.. That were the problems. Now the ritual worked, thank you! I suggest not checking order of budding blocks at all, just check that there are four types of blocks around somewhere, that way the ritual will be easier to understand and accomplish.

**Comment by AetherLegacyPro** [comment]
I am not sure how to word it in the echo block class so it does not matter the direction but require all 4 buddling blocks and clusters present as I would much rather have the direction not matter.
